<?php
  
/**
* Implements hook_theme().
*/
function mypartner_theme($existing, $type, $theme, $path) {
 return array(
   'mypartner_theme' => array( // Theme name
    'variables' => array( // Array of name for varialbles
        'data' => NULL,
        'var1' => NULL,
    ),
    'template' => 'mypartner-theme', // Path to the template without .html.twig in which the same variables will be available as specified above
   ),
   'mypartner_add_theme' => array( // Theme name
    'variables' => array( // Array of name for varialbles
        'data' => NULL,
        'var1' => NULL,
    ),
    'template' => 'mypartner-add-theme', // Path to the template without .html.twig in which the same variables will be available as specified above
    ),
    'mypartner_edit_theme' => array( // Theme name
    'variables' => array( // Array of name for varialbles
        'data' => NULL,
        'var1' => NULL,
    ),
    'template' => 'mypartner-edit-theme', // Path to the template without .html.twig in which the same variables will be available as specified above
    ),
 );
}